version: '3'
services:
  client:
    build: .
    environment:
      - BACKEND_URL=http://backend:80  # replace with the URL of your backend
      - FQDN=example.yourdomain.tld
      # - IP=1.2.3.4  # optional static IP variant
