version: '3'
services:
  client:
    image: nmbit/hetzner-dyndns-client
    container_name: dyndns
    restart: unless-stopped
    # build: .
    environment:
      - BACKEND_URL=http://backend:80  # replace with the URL of your backend
      - FQDN=example.yourdomain.tld
      - PRE_SHARED_KEY=
      # - IP=1.2.3.4  # optional static IP variant
      # update interval in seconds
      - INTERVAL=3600
