version: '3'
services:
  backend:
    image: nmbit/hetzner-dyndns-backend
    container_name: dyndns
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - "8000:80"
    env_file:
      - ./.secrets
